USE codeup_test_db;
TRUNCATE albums,
INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michale Jackson', 'Thriller', '1982', '50.2', 'Pop, post_disco, funk, rock.'),
       ('AC/DC', 'Back in Black', '1980', '30.1', 'Hard Rock'),
       ('Whitney Houston / various artists', 'The Bodyguard', '1992','28.7','R&B, soul, pop, soundtrack'),
       ('Eagles','Their Greatest Hits (1971–1975)','1976','44','Country rock, soft rock, folk rock'),
       ('Pink Floyd','The Dark Side of the Moon','1973','44','Progressive rock'),
       ('Eagles','Hotel California','1976','44','soft rock'),
       ('Shania Twain','Come On Over','1997','40','Country, pop'),
       ('Fleetwood Mac','Rumours','1977','40','Soft Rock'),
       ('Bee Gees / Various artists','Saturday Night Fever','1977','40','Disco'),
       ('Various artists','Grease: The Original Soundtrack from the Motion Picture','1978','38','Rock and Roll'),
       ('Led Zeppelin','Led Zeppelin IV','1971','37','Hard rock, heavy metal, folk rock'),
       ('Michael Jackson','Bad','1987','35','Pop, rhythm and blues, funk and rock'),
       ('Alanis Morissette','Jagged Little Pill','1995','33','Alternative rock'),
       ('Celine Dion','Falling into You','1996','32','Pop, soft rock'),
       ('The Beatles', 'Sgt. Pepper"s Lonely Hearts Club Band', '1967', 18.3, 'Rock'),
       ('Patrick Swazy', 'Dirty Dancing', '1987', 17.9, 'Pop'),
       ('Michael Jackson', 'Dangerous', '1991', 17.0, 'Pop'),
       ('Adele', '21', '2011', 27.1, 'Pop'),
       ('The Beatles', '1', 2000, 23.2, 'Rock'),
       ('Metallica', 'Metallica', '1991', 22.7, 'Heavy Metal'),
       ('Celine Dion', 'Let''s Talk About Love', '2000', 19.5, 'Pop'),
       ('The Beatles', 'Abbey Road', '1969', 16.8, 'Rock'),
       ('Guns N'' Roses', 'Appetite for Destruction', '1987', 22.8, 'Hard Rock'),
       ('Bruce Springsteen', 'Born in the U.S.A', '1984', 22, 'Heartland Rock'),
       ('Meat Loaf', 'Bat Out of Hell', '1977', 22, 'Hard Rock'),
       ('ABBA', 'Gold: Greatest Hits', '1992', 21, 'Pop'),
       ('Dire Straits', 'Brothers in Arms', '1985', 20.8, 'Roots Rock'),
       ('Santana', 'Supernatural', '1999', 20.8, 'Latin Rock'),
       ('Madonna', 'The immaculate Collection', '1990', 19.5, 'Pop'),
       ('Pink Floyd', 'The Wall', '1979', 18.9, 'Progressive Rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture', '1997', 18.1, 'Film Score'),
       ('Nirvana', 'Nevermind', '1991', 17.5, 'Grunge');